<?xml version="1.0" encoding="utf-8"?><Database Name="BD_Project" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-LKBFME05;Initial Catalog=BD_Project;Integrated Security=True" SettingsObjectName="database_layer.Properties.Settings" SettingsPropertyName="BD_ProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.login_tab" Member="login_tab">
    <Type Name="login_tab">
      <Column Name="login" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>